#!/bin/bash
set -euo pipefail

docker run --rm --privileged aptman/qus -s -- -p aarch64

TAG="$(date -u +%Y%m%dT%H%M%SZ)"
echo "$TAG" > .tag
docker build -t brimstone/multiarch:amd64-${TAG} .
docker build -t brimstone/multiarch:aarch64-${TAG} --build-arg=ARCH=aarch64 .
