#!/bin/bash
set -euo pipefail
docker push brimstone/multiarch

TAG="$(< .tag)"

docker manifest create brimstone/multiarch:latest \
	brimstone/multiarch:amd64-"${TAG}" \
	brimstone/multiarch:aarch64-"${TAG}"
docker manifest annotate brimstone/multiarch:amd64-"${TAG}" --os linux --arch amd64
docker manifest annotate brimstone/multiarch:aarch64-"${TAG}" --os linux --arch arm64
