name: build
on:
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup binfmt
      run: docker run --rm --privileged aptman/qus -s
    - name: build image
      run: docker build --build-arg=ARCH=aarch64 -t brimstone/multiarch .
