name: build
on:
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup binfmt
      run: docker run --rm --privileged aptman/qus -s
    - name: build image
      uses: docker/build-push-action@v1
      with:
        push: false
        build_args: ARCH=aarch64
